#!/usr/bin/python3

# Either loop over all IPs or loop only over a certain set
# defined by the label argument passed from commandline.
#
# The loop runs a http request and the exit code is used to
# decide if the host is reachable or not.
#
# The list if IPs is hardcoded in dict style with each matching
# label as a value to the IP.

import sys
import requests
import http.server
import socketserver
import os

### presets
def set_global_vars():
    global basedir
    global config
    global server_dir
    global port
    basedir = '/my/realitycheck/'
    config = str(basedir + 'config')
    server_dir = basedir
    port = 666
### preflight checks
def preflight_checks():
    if len(sys.argv) > 2:
        print(f"too many arguments given") #debug
        sys.exit(2)
    if not os.path.isfile(config):
        print(f"Missing config file: {config}") #debug
        sys.exit(2)
### sys.args handling
def set_method():
    global method
    if len(sys.argv[1:]) == 0:
        method = 'all'
        return
    for arg in sys.argv[1:]:
        if arg == 'server':
            method = 'server'
        else:
            method = str(arg)
### Reading config files
def make_address_dict():
    global address_dict
    address_dict = {}
    f = open(config, 'r')
    for line in f:
        address_dict[(line.rstrip().split())[0]] = (line.rstrip().split())[1:]
### Server part
def start_server():
    handler = http.server.SimpleHTTPRequestHandler
    os.chdir(server_dir)
    try:
        with socketserver.TCPServer(("", port), handler) as httpd:
            httpd.serve_forever()
    except:
        sys.exit(2)
### Client part
def find_target_ip(method):
    global target_ip
    target_ip = []
    if method == 'all':
        for ip in address_dict.keys():
            target_ip.append(ip)
    else:
        for ip,label in address_dict.items():
            if method in label:
                target_ip.append(ip)
### Send the request, return index.html
def send_request(ip):
    try:
        r = requests.get('http://' + ip + ':666', timeout=2)
        if r.status_code != 200:
            print(f"unexpected status code returned: {r.status_code}") #debug
        else:
            print(f"{ip} is reachbale") #debug
            print(f"index.html: {r.text.rstrip()}") #debug
    except:
            print(f"server {ip} not reachable") #debug

# Main
if __name__ == '__main__':
    set_global_vars()
    preflight_checks()
    set_method()
    make_address_dict()
    if method == 'server':
        start_server()
    else:
        find_target_ip(method)
    for ip in target_ip:
        send_request(ip)
